[package]
name = "grit_read"
version = "0.1.0"
authors = ["casept <davids.paskevics@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_riff = {git = "https://github.com/casept/tiny_riff"}
